export const sceneArr = [
  {
    tile: 1,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 2,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 3,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 4,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 5,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 6,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 7,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 8,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 9,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 10,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 11,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 12,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 13,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 14,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 15,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 16,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 17,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 18,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 19,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 20,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 21,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 22,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 23,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 24,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 25,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 26,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 27,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 28,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 29,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 30,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 31,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 32,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 33,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 34,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 35,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 36,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 37,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 38,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 39,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
  },
  {
    tile: 40,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
  },
  {
    tile: 41,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 42,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 43,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 44,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 45,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 46,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
  },
  {
    tile: 47,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 48,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 49,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 50,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
  },
  {
    tile: 51,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
  },
  {
    tile: 52,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
  },
  {
    tile: 53,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
  },
  {
    tile: 54,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
  },
  {
    tile: 55,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
    location: 10,
  },
  {
    tile: 56,
    description: "A newspaper",
    item: true,
    move: true,
    imageUrl: "./assets/newspaper.png",
  },
  {
    tile: 57,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
  },
  {
    tile: 58,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 59,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
  {
    tile: 60,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
  },
];
