export const sceneArr = [
  {
    tile: 1,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 5,
    yLocation: 5,
  },
  {
    tile: 2,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 5,

    yLocation: 15,
  },
  {
    tile: 3,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 5,

    yLocation: 25,
  },
  {
    tile: 4,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 5,

    yLocation: 35,
  },
  {
    tile: 5,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 5,

    yLocation: 45,
  },
  {
    tile: 6,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 5,

    yLocation: 55,
  },
  {
    tile: 7,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 5,

    yLocation: 65,
  },
  {
    tile: 8,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 5,

    yLocation: 75,
  },
  {
    tile: 9,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 5,

    yLocation: 85,
  },
  {
    tile: 10,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 5,

    yLocation: 95,
  },
  {
    tile: 1,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 11,
    yLocation: 5,
  },
  {
    tile: 2,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 11,
    yLocation: 15,
  },
  {
    tile: 3,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 11,
    yLocation: 25,
  },
  {
    tile: 4,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 11,
    yLocation: 35,
  },
  {
    tile: 5,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 11,
    yLocation: 45,
  },
  {
    tile: 6,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 11,
    yLocation: 55,
  },
  {
    tile: 7,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 11,
    yLocation: 65,
  },
  {
    tile: 8,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 11,
    yLocation: 75,
  },
  {
    tile: 9,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 11,
    yLocation: 85,
  },
  {
    tile: 10,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 11,
    yLocation: 95,
  },
  {
    tile: 1,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 16,
    yLocation: 5,
  },
  {
    tile: 2,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 16,
    yLocation: 15,
  },
  {
    tile: 3,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 16,
    yLocation: 25,
  },
  {
    tile: 4,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 16,
    yLocation: 35,
  },
  {
    tile: 5,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 16,
    yLocation: 45,
  },
  {
    tile: 6,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 16,
    yLocation: 55,
  },
  {
    tile: 7,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 16,
    yLocation: 65,
  },
  {
    tile: 8,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 16,
    yLocation: 75,
  },
  {
    tile: 9,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 16,
    yLocation: 85,
  },
  {
    tile: 10,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 16,
    yLocation: 95,
  },
  {
    tile: 1,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 22,
    yLocation: 5,
  },
  {
    tile: 2,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 22,
    yLocation: 15,
  },
  {
    tile: 3,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 22,
    yLocation: 25,
  },
  {
    tile: 4,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 22,
    yLocation: 35,
  },
  {
    tile: 5,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 22,
    yLocation: 45,
  },
  {
    tile: 6,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 22,
    yLocation: 55,
  },
  {
    tile: 7,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 22,
    yLocation: 65,
  },
  {
    tile: 8,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 22,
    yLocation: 75,
  },
  {
    tile: 9,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
    xLocation: 22,
    yLocation: 85,
  },
  {
    tile: 10,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
    xLocation: 22,
    yLocation: 95,
  },
  {
    tile: 1,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 27,
    yLocation: 5,
  },
  {
    tile: 2,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 27,
    yLocation: 15,
  },
  {
    tile: 3,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 27,
    yLocation: 25,
  },
  {
    tile: 4,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 27,
    yLocation: 35,
  },
  {
    tile: 5,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 27,
    yLocation: 45,
  },
  {
    tile: 6,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
    xLocation: 27,
    yLocation: 55,
  },
  {
    tile: 7,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 27,
    yLocation: 65,
  },
  {
    tile: 8,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 27,
    yLocation: 75,
  },
  {
    tile: 9,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 27,
    yLocation: 85,
  },
  {
    tile: 10,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
    xLocation: 27,
    yLocation: 95,
  },
  {
    tile: 1,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
    xLocation: 32,
    yLocation: 5,
  },
  {
    tile: 2,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
    xLocation: 32,
    yLocation: 15,
  },
  {
    tile: 3,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
    xLocation: 32,
    yLocation: 25,
  },
  {
    tile: 4,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
    xLocation: 32,
    yLocation: 35,
  },
  {
    tile: 5,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
    xLocation: 32,
    yLocation: 45,
  },
  {
    tile: 6,
    description: "A newspaper",
    item: true,
    move: true,
    imageUrl: "./assets/newspaper.png",
    xLocation: 32,
    yLocation: 55,
  },
  {
    tile: 7,
    description: "Nothing there",
    item: false,
    move: true,
    imageUrl: "",
    xLocation: 32,
    yLocation: 65,
  },
  {
    tile: 8,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 32,
    yLocation: 75,
  },
  {
    tile: 9,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 32,
    yLocation: 85,
  },
  {
    tile: 10,
    description: "Nothing there",
    item: false,
    move: false,
    imageUrl: "",
    xLocation: 32,
    yLocation: 95,
  },
];
